# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e89760ae86e12245e1895baddcc58a078355e5984b63c40110cb4151fa8c7d7a05d2001ea8c09a4869259fd8a6cb1a160d561aa57cae84cb254ea0c3c033bc2

test:
  secret_key_base: ff30d9e5371236db1c42ad2e64c0280eb57892c8ff444274ac51e6cc14efb55b7a5aab694321940e969945c8c03d49ff3432e18511d43224b98bcd589b3a96ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
